[project]
name = "checkpoint-final"
authors = ["Checkpoint Team"]
description = "Decentralized user matching and recommendation protocol"
telemetry = false
requirements = []
[contracts.checkpoint-user-matching]
path = "contracts/checkpoint-user-matching.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
